# CarbonFox - generated by the notch theme selector
# Sourced by ~/.zshrc; do not edit.
typeset -g NOTCH_THEME_NAME='CarbonFox'
typeset -g NOTCH_C_MAUVE='#be95ff'
typeset -g NOTCH_C_BLUE='#78a9ff'
typeset -g NOTCH_C_GREEN='#25be6a'
typeset -g NOTCH_C_RED='#ee5396'
typeset -g NOTCH_C_YELLOW='#08bdba'
typeset -g NOTCH_C_PEACH='#f16da6'
typeset -g NOTCH_C_TEXT='#f2f4f8'
typeset -g NOTCH_C_SUBTEXT='#dfdfe0'
typeset -g NOTCH_C_OVERLAY='#7b7b7b'
