# Gruvbox - generated by the notch theme selector
# Sourced by ~/.zshrc; do not edit.
typeset -g NOTCH_THEME_NAME='Gruvbox'
typeset -g NOTCH_C_MAUVE='#d3869b'
typeset -g NOTCH_C_BLUE='#83a598'
typeset -g NOTCH_C_GREEN='#b8bb26'
typeset -g NOTCH_C_RED='#fb4934'
typeset -g NOTCH_C_YELLOW='#fabd2f'
typeset -g NOTCH_C_PEACH='#fe8019'
typeset -g NOTCH_C_TEXT='#ebdbb2'
typeset -g NOTCH_C_SUBTEXT='#d5c4a1'
typeset -g NOTCH_C_OVERLAY='#928374'
