# Everforest - generated by the notch theme selector
# Sourced by ~/.zshrc; do not edit.
typeset -g NOTCH_THEME_NAME='Everforest'
typeset -g NOTCH_C_MAUVE='#d699b6'
typeset -g NOTCH_C_BLUE='#7fbbb3'
typeset -g NOTCH_C_GREEN='#a7c080'
typeset -g NOTCH_C_RED='#e67e80'
typeset -g NOTCH_C_YELLOW='#dbbc7f'
typeset -g NOTCH_C_PEACH='#e69875'
typeset -g NOTCH_C_TEXT='#d3c6aa'
typeset -g NOTCH_C_SUBTEXT='#9da9a0'
typeset -g NOTCH_C_OVERLAY='#859289'
