.pragma library

// Turn a notch palette into the config files consumed by kitty and nvim.

function kitty(palette, name) {
	const p = palette;
	return [
		"# " + name + " - generated by the notch theme selector",
		"foreground " + p.text,
		"background " + p.base,
		"selection_foreground " + p.base,
		"selection_background " + p.surface1,
		"cursor " + p.pink,
		"cursor_text_color " + p.base,
		"url_color " + p.teal,
		"active_border_color " + p.blue,
		"inactive_border_color " + p.overlay0,
		"bell_border_color " + p.yellow,
		"active_tab_foreground " + p.base,
		"active_tab_background " + p.mauve,
		"inactive_tab_foreground " + p.subtext,
		"inactive_tab_background " + p.surface0,
		"tab_bar_background " + p.crust,
		"mark1_foreground " + p.base,
		"mark1_background " + p.blue,
		"mark2_foreground " + p.base,
		"mark2_background " + p.mauve,
		"mark3_foreground " + p.base,
		"mark3_background " + p.teal,
		"color0 " + p.surface1,
		"color8 " + p.overlay0,
		"color1 " + p.red,
		"color9 " + p.red,
		"color2 " + p.green,
		"color10 " + p.green,
		"color3 " + p.yellow,
		"color11 " + p.yellow,
		"color4 " + p.blue,
		"color12 " + p.blue,
		"color5 " + p.mauve,
		"color13 " + p.mauve,
		"color6 " + p.teal,
		"color14 " + p.teal,
		"color7 " + p.subtext,
		"color15 " + p.text
	].join("\n") + "\n";
}

function nvimPalette(palette) {
	const p = palette;
	const map = {
		bg: p.base,
		bg_dark: p.crust,
		surface: p.surface0,
		overlay: p.surface1,
		border: p.hairline,
		fg: p.text,
		fg_dim: p.subtext,
		gray: p.overlay0,
		red: p.red,
		orange: p.peach,
		yellow: p.yellow,
		green: p.green,
		cyan: p.teal,
		blue: p.blue,
		purple: p.mauve,
		pink: p.pink,
		selection: p.surface0
	};

	let out = "-- generated by the notch theme selector\nreturn {\n";
	for (const key in map)
		out += "\t" + key + " = \"" + map[key] + "\",\n";
	out += "}\n";
	return out;
}

// tmux: status line + pane borders (sourced from ~/.tmux-theme.conf).
function tmux(palette, name) {
	const p = palette;
	return [
		"# " + name + " - generated by the notch theme selector",
		"set-option -g status-style \"bg=default,fg=" + p.mauve + "\"",
		"set-option -g window-status-style \"bg=default,fg=" + p.overlay0 + "\"",
		"set-option -g window-status-current-style \"bg=default,fg=" + p.mauve + ",bold\"",
		"set-option -g pane-border-style \"fg=" + p.surface0 + "\"",
		"set-option -g pane-active-border-style \"fg=" + p.mauve + "\""
	].join("\n") + "\n";
}

// pi coding agent theme (its active theme file is hot reloaded on edit).
function pi(palette, name) {
	const p = palette;
	const vars = {
		mauve: p.mauve,
		blue: p.blue,
		sky: p.teal,
		pink: p.pink,
		red: p.red,
		peach: p.peach,
		yellow: p.yellow,
		green: p.green,
		teal: p.teal,
		text: p.text,
		subtext: p.subtext,
		overlay: p.overlay0,
		surface1: p.surface1,
		surface0: p.surface0,
		base: p.crust,
		mantle: p.mantle
	};
	const colors = {
		accent: "mauve",
		border: "surface0",
		borderAccent: "mauve",
		borderMuted: "surface0",
		success: "green",
		error: "red",
		warning: "yellow",
		muted: "subtext",
		dim: "overlay",
		text: "",
		thinkingText: "subtext",
		selectedBg: "surface0",
		searchMatchBg: "surface1",
		searchMatchText: "text",
		userMessageBg: "mantle",
		userMessageText: "",
		customMessageBg: "mantle",
		customMessageText: "",
		customMessageLabel: "mauve",
		toolPendingBg: "mantle",
		toolSuccessBg: "mantle",
		toolErrorBg: "mantle",
		toolTitle: "mauve",
		toolOutput: "",
		mdHeading: "mauve",
		mdLink: "blue",
		mdLinkUrl: "overlay",
		mdCode: "pink",
		mdCodeBlock: "",
		mdCodeBlockBorder: "surface0",
		mdQuote: "subtext",
		mdQuoteBorder: "mauve",
		mdHr: "surface0",
		mdListBullet: "teal",
		toolDiffAdded: "green",
		toolDiffRemoved: "red",
		toolDiffContext: "subtext",
		syntaxComment: "overlay",
		syntaxKeyword: "mauve",
		syntaxFunction: "blue",
		syntaxVariable: "text",
		syntaxString: "green",
		syntaxNumber: "peach",
		syntaxType: "yellow",
		syntaxOperator: "sky",
		syntaxPunctuation: "overlay",
		thinkingOff: "overlay",
		thinkingMinimal: "subtext",
		thinkingLow: "blue",
		thinkingMedium: "sky",
		thinkingHigh: "mauve",
		thinkingXhigh: "pink",
		thinkingMax: "red",
		bashMode: "peach"
	};
	return JSON.stringify({
		"$schema": "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
		name: name,
		vars: vars,
		colors: colors,
		export: { pageBg: p.crust, cardBg: p.mantle, infoBg: p.surface0 }
	}, null, 2) + "\n";
}
