pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "Themes.js" as Themes
import "ThemeGen.js" as ThemeGen

// Source of truth for the active theme. Writes the generated kitty/nvim files
// and pokes kitty to reload; the shell reads colors straight from `palette`.
Singleton {
    readonly property string home: String(Quickshell.env("HOME"))
    readonly property string configDir: home + "/.config"
    readonly property string currentFile: configDir + "/themes/current"

    property string currentId: Themes.defaultId

    readonly property var theme: Themes.get(currentId)
    readonly property var palette: theme.palette
    readonly property string themeName: theme.name

    function setCurrent(id) {
        if (Themes.all[id] !== undefined)
            currentId = id;
    }

    function activate(id) {
        if (Themes.all[id] === undefined)
            return;
        currentId = id;

        const t = Themes.get(id);
        writeFile(currentFile, id + "\n");
        writeFile(configDir + "/kitty/theme.conf", ThemeGen.kitty(t.palette, t.name));
        writeFile(configDir + "/nvim/notch-palette.lua", ThemeGen.nvimPalette(t.palette));
        writeFile(home + "/.tmux-theme.conf", ThemeGen.tmux(t.palette, t.name));
        writeFile(home + "/.zsh-theme.zsh", ThemeGen.zsh(t.palette, t.name));
        // zathura keeps its colours in a separate file that zathurarc includes,
        // so a user's own zathura settings are never rewritten.
        writeFile(configDir + "/zathura/notch-theme", ThemeGen.zathura(t.palette, t.name));
        ensureZathuraInclude(configDir + "/zathura");
        // A single stable pi theme file: pi hot reloads the active theme file
        // when it is rewritten, so keep the name fixed at "notch".
        writeFile(home + "/.pi/agent/themes/notch.json", ThemeGen.pi(t.palette, "notch"));

        Quickshell.execDetached(["pkill", "-USR1", "-x", "kitty"]);
        Quickshell.execDetached(["tmux", "source-file", home + "/.tmux-theme.conf"]);
    }

    // zathura reads no ~/.config/zathura/zathurarc by default here, so create one
    // that pulls in the generated colours. Idempotent: an existing zathurarc is
    // left alone apart from gaining the include line once, and grep guards
    // against appending it on every theme switch.
    function ensureZathuraInclude(dir) {
        const script = [
            'mkdir -p "$1"',
            'f="$1/zathurarc"',
            'line="include $1/notch-theme"',
            'if [ ! -e "$f" ]; then',
            '  printf "%s\\n" "# theme colours: generated by the notch theme selector" "$line" > "$f"',
            'elif ! grep -qF "notch-theme" "$f"; then',
            '  printf "%s\\n" "" "# theme colours: generated by the notch theme selector" "$line" >> "$f"',
            'fi'
        ].join("\n") + "\n";
        Quickshell.execDetached(["sh", "-c", script, "--", dir]);
    }

    // Write via a quoted heredoc so arbitrary text survives the shell untouched.
    function writeFile(path, content) {
        const body = content + (content.endsWith("\n") ? "" : "\n");
        const script = "mkdir -p \"$(dirname \"$1\")\"\n"
            + "cat > \"$1\" <<'NOTCH_THEME_EOF'\n"
            + body
            + "NOTCH_THEME_EOF\n";
        Quickshell.execDetached(["sh", "-c", script, "--", path]);
    }

    Process {
        id: loader

        command: ["sh", "-c", "cat \"" + currentFile + "\" 2>/dev/null || true"]
        running: true

        stdout: StdioCollector {
            onStreamFinished: setCurrent(text.trim())
        }
    }
}
